name: Build

on: 
  push:
    branches: [ master ]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: ${{ matrix.config.name }}-${{ matrix.config.compiler }}-${{ matrix.config.version }}
    runs-on: ${ { matrix.config.os } }
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: window-latest
            compiler: msvc  
          - os: ubuntu-18.04
            compiler: gcc
            version: "7.4"
          - os: macOS-latest
            compiler: clang
            version: "8"
    steps:
      - name: Configure
        run: |
            mkdir build
            cd build
            cmake .. -GNinja -DCMAKE_BUILD_TYPE:Release
      - name: Build
        run: ninja
      - name: Test
        run: |
            cd build
            ./main
