name: C++ CI

on: push

defaults:
  run:
    shell: bash

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        config: [Release]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup C++ environment
        uses: kurocha/setup-cpp@v1

      - name: Build c++ project
        uses: nicledomaS/cmake_build_action@v1.4
        with:
          config: ${{ matrix.config }}
          run_tests: ON
          create_package: ON
          package_generator: ZIP

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          path: build/*.zip
          name: artifact_${{ matrix.os }}_${{ matrix.config }}.zip