name: Build

on: 
  push:
    branches: [ master ]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        configs: [Release]
    steps:
      - uses: actions/checkout@v2
      - name: Get latest CMake and ninja
        uses: lukka/get-cmake@latest 
      - name: Build & Test
        uses: ashutoshvarma/action-cmake-build@master
        with:
          build-dir: ${{ runner.workspace }}/build
          cxx: g++
          build-type: Release
          run-test: true
          ctest-options: -R mytest
          install-build: true
    