name: C++ CI

on: 
  push:
    branches: [ master ]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: cmake-clang-ninja-build
        uses: UnsafePointer/cmake-clang-ninja-build-github-action@v1.4