name: C++ CI

on: push

defaults:
  run:
    shell: bash

jobs:
  build:
    name: ${{ matrix.os }}_${{ matrix.build_type }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Release, Debug]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Ninja & CMake
        uses: lukka/get-cmake@v3.20.1

      - name: Setup C++ environment
        uses: kurocha/setup-cpp@v1

      - name: Configure CMake
        run: cmake . --preset ${{ matrix.build_type }}

      - name: Build
        run: cmake --build --preset ${{ matrix.build_type }}
      
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          path: build/${{ matrix.build_type }}/*.zip
          name: artifact_${{ matrix.os }}_${{ matrix.build_type }}.zip