name: C++ CI

on: push

defaults:
  run:
    shell: bash

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - { name: "Windows MSVC", os: windows-latest, cxx: "cl" }
          - { name: "Ubuntu gcc", os: ubuntu-latest, cxx: "g++" }
          - { name: "MacOS clang", os: macos-latest, cxx: "clang++" }
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@v1.1

      - name: Build with CMake
        uses: ashutoshvarma/action-cmake-build@master
        with:
          build-dir: ${{ runner.workspace }}/build
          cxx: ${{ matrix.config.cxx }}
          configure-options: -G Ninja
          build-type: Release
