name: C++ CI

on: [push]

jobs:  
  runs-on: ${{ matrix.os }}
  strategy:
    matrix:
      os: [ubuntu-latest, windows-latest, macos-latest]
      configs: [Release, Debug]
  steps:
    - name: Checkout
      uses: action/checkout@v2.0.0
      
    - name: Build project
      uses: nickeldomaS/cmake_build_action@v1.4
      with:
        config: ${{ matrix.configs }}
        submodule_update: ON
        run-tests: ON
        unit_test_build: -DFIND_TESTS=ON
        cmake_args: -DFIND_MODULES=ON;-DENABLE_TIDY=ON
        create_package: ON
    - uses: action/upload-artifact@v2
      with:
        path: build/*.zip
        name: artifact_${{ matrix.os }}_${{ matrix.configs }}.zip